[package]
name = "password-game-clone"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.8.5"
sycamore = "0.8.2"
getrandom = { version = "0.2", features = ["js"] }